name: GitHub Pages

on:
  push:
    branches:
      - main  # Убедитесь, что указана правильная ветка (main или master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Загрузка репозитория
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Загружаем всю историю коммитов

      # Шаг 2: Установка Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # Используем последнюю версию Hugo
          extended: true          # Используем расширенную версию Hugo

      # Шаг 3: Сборка сайта
      - name: Build
        run: hugo --minify  # Минификация выходных файлов

      # Шаг 4: Публикация на GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Токен для доступа к репозиторию
          publish_dir: ./public  # Папка с собранным сайтом